### PR TITLE
[ADD] Postgres 16 Support

### PR DESCRIPTION
**Pull request by oskardotglobal**
After the chaos in #17 I decided to just PR this myself.
I'll have to make some changes, but this should be ready to go soon.

### CODE REVIEW

**Comment by pleirb** [comment]
> After the chaos in #17 I decided to just PR this myself. I'll have to make some changes, but this should be ready to go soon.

Thank you so much !
Will this soon be available in the doodba-copier-template project as well?

**Comment by oskardotglobal** [comment]
Once this is merged that will definitely be possible, but I will not PR those changes myself as I don't use that template.

**Comment by bosd** [comment]
@oskardotglobal Can you clean up this pr? Please remove unnessecary commits.
Please keep V14
& squash the commits?  🙏

**Comment by josep-tecnativa** [comment]
You could base your PR on this https://github.com/Tecnativa/docker-postgres-autoconf/commit/8179fde3783dd34939c7fa6015199dc2be80092f as it is analogous to what you want to do, but with Postgres 15.

**Comment by oskardotglobal** [comment]
@bosd I will squash the commits. I seem to have removed V14 accidentally, I will readd this.

@josep-tecnativa Thank you for the suggestion, but I think moving the build steps to actions from the python scripts is a much cleaner solution. I will still update the tests accordingly.

**Comment by oskardotglobal** [comment]
I don't think I can do that in a simple way; I've rewritten history in my local repo and force-pushed the remote

**Comment by pedrobaeza** [comment]
@josep-tecnativa what about this?

**Comment by josep-tecnativa** [comment]
Since we needed to have PG 16 quickly, I made another PR and merged it. If you can modify this PR or create a new one with changes that are not related to PG 16, I will review it.

**Pull request closed without merging**
