### PR TITLE
[ADD] pg15

### PR DESCRIPTION
**Pull request by Tardo**
Add the latest version of psql

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why there isn't CI? Can you rebase and push again?

**Comment by Tardo** [comment]
Ooops no, the line above just says for pr's....

**Comment by Tardo** [comment]
Ummm... Maybe github has auto-disabled CI for this repo due to inactivity?

Latest was 6 months ago: https://github.com/Tecnativa/docker-postgres-autoconf/actions

**Comment by pedrobaeza** [comment]
I see that there's no checks for this, so let's merge and see the pushed docker images.

**Pull request merged**
